### ISSUE TITLE
Add remote method generator

### ISSUE THREAD

**Issue by superkhau** [strongloop/generator-loopback#94]
We should add the `slc loopback:remote-method` command to scaffold custom remote methods.

See #90 

**Subtasks**
- [x] First cut implementation
- [x] Http mapping of arguments (see https://docs.strongloop.com/display/public/LB/Remote+methods?src=search&src=search#Remotemethods-HTTPmappingofinputarguments)
- [x] Add `isStatic`
- [x] Check input valid
- [x] Add unit tests
- [x] Either add a dummy method implementation to model js file or alternatively print instructions including dummy method code to the output after the JSON metadata was updated.
- [x] Add http verb(major and custom)
- [x] Make modelName an argument

**Comment by bajtos** [comment]
It would be good to land https://github.com/strongloop/loopback/pull/1163 first.

**Comment by jannyHou** [comment]
A record for subtasks:
- [x] first cut implementation
- [ ] http mapping of arguments
- [ ] add `isStatic`
- [ ] check input valid

**Comment by bajtos** [comment]
@jannyHou I moved the list of subtasks to issue description to keep them at the top.

**Comment by bajtos** [comment]
@jannyHou Nice start in #124! Please continue with adding tests for the new generator as it is implemented now before working on additional features.

**Comment by jannyHou** [comment]
@bajtos yeah good to have them on top, thanks a lot! I would add tests first, then move to features.

**Comment by bajtos** [comment]
@jannyHou can we close this issue now, since #124 has been landed?

**Comment by jannyHou** [comment]
@bajtos sure, thank your for reviewing the pr and guiding me to improve the implementation! since it's landed I will close the issue here.
